data:
    dataset: "AUDIO"
    image_size: 256
    channels: 2
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 4
    path: "downloads"
    virtual_samplerate: 48000

model:
    type: "simple"
    in_channels: 2
    out_ch: 2
    ch: 32
    ch_mult: [1, 1, 2, 4, 4, 6]
    krn_size: [3, 3, 7, 13, 3, 3]
    num_res_blocks: [2, 2, 6, 12, 2, 2]
    attn_resolutions: [8, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 6
    n_epochs: 1000
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000

sampling:
    batch_size: 64
    last_only: True

optim:
    weight_decay: 0.0000001
    optimizer: "AdaBelief"
    lr: 0.0001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: null
    clip_step: 1
    norm_ord: 2
