define: &f_size 256
define: &low_level_ch 2
define: &t_size 1024
define: &axis_format TFC
define: &virtual_samplerate 48000
define: &HPI False


data:
    dataset: AUDIO
    path: downloads
    dataset_kwargs:
        f_size: *f_size
        t_size: *t_size
        virtual_samplerate: *virtual_samplerate
        use_numpy: False
        dtype: torch.bfloat16
        device: cuda
        axis: *axis_format
        HPI: *HPI
    num_workers: 0

    log_polar_transform: True
    normalize_dim: [0, 1] # or null

model:
    dtype: torch.cuda.BFloat16Tensor
    type: simple

    transformers:
        kwargs:
            local_kernel_size: 32
            segment_size: 256

            hidden_size: 768
            num_hidden_layers: 12
            intermediate_size: 1536
            hidden_dropout_prob: 0.1
            initializer_range: 0.02
            layer_norm_eps: 0.00000001
        channels: 768
        dtype: torch.cuda.BFloat16Tensor

    channels: *low_level_ch
    t_size: *t_size
    f_size: *f_size

diffusion:
    training_beta: "np.linspace(1e-6, 6e-3, 1000)"
    sampling_beta: "np.asarray([j*10**i for i in range(-6, 0) for j in [1, 2, 4, 6, 8]])"

training:
    batch_size: 128
    n_epochs: null
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000

sampling:
    batch_size: 64
    last_only: True
    denoise: True
    HPI: *HPI
    virtual_samplerate: *virtual_samplerate

    num_samples: 2
    t_size: 8192

optimization:
    optimizer:
        transformer:
            top_level_name:
                - transformer
            weight_decay: 0.00001
            optimizer: "AdamW"
            warmup: 10000
            lr: 0.0005
            min_rate: 0.2
            beta: [0.9, 0.999]
            amsgrad: false
            eps: 0.00000001
        default:
            top_level_name: []
            weight_decay: 0.00001
            optimizer: "AdamW"
            warmup: 10000
            lr: 0.0005
            min_rate: 0.2
            beta: [0.9, 0.999]
            amsgrad: false
            eps: 0.00000001
    
    grad_norm:
        transformer:
            top_level_name: []
            grad_clip: 1
        default:
            top_level_name: []
            grad_clip: 1